// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Collapse: typeof import('./src/components/common/Collapse.vue')['default']
    Collapses: typeof import('./src/components/common/Collapses.vue')['default']
    Collaspe: typeof import('./src/components/common/collaspe.vue')['default']
    CoverPlay: typeof import('./src/components/common/CoverPlay.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    EleIcon: typeof import('./src/components/common/EleIcon.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIcons: typeof import('@element-plus/icons-vue')['s']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/footer/index.vue')['default']
    Header: typeof import('./src/components/layout/header/index.vue')['default']
    HeaderSearch: typeof import('./src/components/layout/header/headerSearch/index.vue')['default']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    Layout: typeof import('./src/components/layout/layout.vue')['default']
    Main: typeof import('./src/components/layout/main/index.vue')['default']
    Menu: typeof import('./src/components/layout/menu/index.vue')['default']
    MoreText: typeof import('./src/components/common/MoreText.vue')['default']
    PlayerAction: typeof import('./src/components/layout/footer/PlayerAction.vue')['default']
    PlayerController: typeof import('./src/components/layout/footer/PlayerController.vue')['default']
    PlayerList: typeof import('./src/components/layout/footer/PlayerList.vue')['default']
    PlayerSlider: typeof import('./src/components/layout/footer/PlayerSlider.vue')['default']
    PlayerSongInfo: typeof import('./src/components/layout/footer/PlayerSongInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSuggest: typeof import('./src/components/layout/header/headerSearch/SearchSuggest.vue')['default']
    Title: typeof import('./src/components/common/Title.vue')['default']
    UserInfo: typeof import('./src/components/layout/header/userInfo/index.vue')['default']
  }
}
